accounts/urls.py
from django.conf.urls import url
from . import views
from django.urls import reverse_lazy

from django.contrib.auth.views import (
    LoginView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)

urlpatterns = [
    # Страница входа.
    url(r'^login/$', LoginView.as_view
    (template_name='accounts/registration/login.html'), name='login'),
    # Страница выхода.
    url(r'^logout/$', views.logout_view, name='logout'),
    #регистрация вроде, как...
    url(r'^signup/$', views.signup, name='signup'),
    # ссылка на изменение имяни, фамилии и почты вобщем настройки аккаунта
    url(r'^accounts/profile/$', views.edit_account, name='my_account'),


    # смена пароля под своим аккаунтом
    url(r'^password-change/$', PasswordChangeView.as_view(
        template_name='accounts/registration/password_change.html',
        success_url=reverse_lazy('accounts:password_change_done')
    ),
        name='password_change'),

    url(r'^password-change-done/$', PasswordChangeDoneView.as_view(
        template_name='accounts/registration/password_change_done.html'),
        # если что лизи
        name='password_change_done'),

    # Если забыли пароль вот это всё решит ваши проблемы |
    url(r'^password-reset/$', PasswordResetView.as_view(
        template_name='accounts/registration/password_reset.html',
        email_template_name='accounts/registration/password_reset_email.html',
        success_url=reverse_lazy('accounts:password_reset_done'),
    ),
        name='password_reset'),

    url(r'^password-reset/done/$', PasswordResetDoneView.as_view(
        template_name='accounts/registration/password_reset_done.html',),
        name='password_reset_done'),

    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        PasswordResetConfirmView.as_view(
            template_name='accounts/registration/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'),

    url(r'^password-reset/complete/$',
        PasswordResetCompleteView.as_view(
            template_name='accounts/registration/password_reset_complete.html',
        ),
        name='password_reset_complete'),


    # только так сначало фолловерз, а потом все для него иначе джскрипт не сработает
    url(r'^users/followers/$', views.user_follow, name='user_follow'),

    # лист пользователей
    url(r'^users/$', views.user_list, name='user_list'),

    # конкретный юзер
    url(r'^users/(?P<username>[-\w]+)/$',
        views.user_detail, name='user_detail'),
    # новости по сути
    url(r'^track/$', views.track, name='track'),




]

images/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # создание картинки для сайта спомощю джаваскрипта
    url(r'^create/$', views.image_create, name='create'),
    # детали картинки если слунга не будет будет ошибка!!
    url(r'^detail/(?P<slug>[-\w]+)/$', views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    #url(r'^ranking/$', views.image_ranking, name='create'),
    # поидее все картинки с панигацией, но посмотрим
    url(r'^$', views.image_list, name='list'),
]

my_blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from django.contrib.sitemaps.views import sitemap
from python4bear.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'', include('python4bear.urls', namespace='python4bear')),
    url(r'', include('accounts.urls', namespace='accounts')),
    url(r'', include('search.urls', namespace='search')),
    url(r'^images/', include('images.urls', namespace='images')),
    url(r'^polls/', include('polls.urls', namespace='polls')),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    url('^', include('django.contrib.auth.urls')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.
from django.conf import settings
from versatileimagefield.fields import VersatileImageField, PPOIField
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True, verbose_name='ДР')
    photo = VersatileImageField(upload_to='users/%Y/%m/%d', blank=True,
                                ppoi_field='ppoi', verbose_name='')
    ppoi = PPOIField(
        'Image PPOI'
    )

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

class Contact(models.Model):
    user_from = models.ForeignKey(User, related_name='rel_from_set')
    user_to = models.ForeignKey(User, related_name='rel_to_set')
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def str (self):
        return '{} followers {}'.format(self.user_from,
                                      self.user_to)

# добавить следующее поле пользователю динамически «monkey patch»
User.add_to_class('following',
                  models.ManyToManyField('self',
                                         through=Contact,
                                         related_name='followers',
                                         symmetrical=False))

accounts/forms.py
from django import forms

from django.contrib.auth.models import User

from .models import Profile

class UserForm(forms.ModelForm):
    """Форма юзера..."""
    email = forms.EmailField( max_length=50, required=True, )
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'password2']

    def clean_password2(self):
        word = self.cleaned_data
        if word['password'] != word['password2']:
            raise forms.ValidationError('Пароли не совпадают.')
        return word['password']

    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError(("Пользователь с таким email уже существует!"))

class UserFormForEdit(forms.ModelForm):
    """Форма для редактирования юзера, не все поля доступны специально"""
    email = forms.EmailField(max_length=50, required=True, )
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email',]

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo',]

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate

from accounts.forms import UserForm, ProfileEditForm, UserFormForEdit
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User

from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from .models import Contact

from actions.utils import create_action
from actions.models import Action

from django.http import HttpResponse, JsonResponse
from django.core.paginator import Paginator, EmptyPage, \
PageNotAnInteger

# Create your views here.
def logout_view(request):
    """Завершает сеанс работы с приложением."""
    logout(request)
    return HttpResponseRedirect(reverse('python4bear:home'))


def signup(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Показать пустую регестрационную форму
        form = UserForm()
    else:
        # Обработка заполненной формы.
        form = UserForm(request.POST)

        if form.is_valid():
            new_user = form.save(commit=False)
            # Set the chosen password
            new_user.set_password(form.cleaned_data['password'])
            new_user.email = form.cleaned_data['email']
            # Save the User object
            new_user.save()
            # Create the user profile
            profile = Profile.objects.create(user=new_user)
            create_action(new_user, 'создал учетную запись тут:)')
            profile.save()# вот это походу не надо он и так создается!или!
            # Выполнение входа и перенаправление на домашнюю страницу
            authenticated_user = authenticate(username=form.cleaned_data['username'],
                                              password=form.cleaned_data['password'])
            login(request, authenticated_user)
            return redirect('python4bear:home')
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)


@login_required
def edit_account(request):
    """Пользовательский аккаунт, его редактирование"""

    user_form = UserFormForEdit(instance=request.user)
    profile_form = ProfileEditForm(instance=request.user.profile)
    if request.method == "POST":
        user_form = UserFormForEdit(request.POST, instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Профиль - обновился!')
        else:
            messages.error(request, 'Error ты, что-то накасячел.')

        return HttpResponseRedirect('{}?sent=True'.format(reverse('accounts:my_account')))

    return render(request, 'accounts/my_account.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })

# @login_required
# def user_list(request):
#     # лист пользователь можно сделать пагинацию!!
#     users = User.objects.filter(is_active=True)
#     return render(request, 'accounts/user/list.html', {'section': 'people',
#                                                       'users': users})


def user_list(request):
    users = User.objects.filter(is_active=True).order_by('id')# если ордер бай ай ди не добавляю возникает ошибка
    paginator = Paginator(users, 4)
    page = request.GET.get('page')
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом
        users = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # Если запрос AJAX и страница вне диапазона
            # вернуть пустую страницу
            return HttpResponse('')
        # Если страница находится вне диапазона доставить последнюю страницу результатов
        users = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,
                      'accounts/user/list_ajax.html',
                      {'section': 'people', 'users': users})
    return render(request,
                  'accounts/user/list.html',
                  {'section': 'people', 'users': users})


@login_required
def user_detail(request, username):
    view_user = get_object_or_404(User, username=username, is_active=True)
    return render(request, 'accounts/user/detail.html', {'section': 'people',
                                                        'view_user': view_user})

@ajax_required
@login_required
@require_POST
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user1 = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user,
                                              user_to=user1)
                create_action(request.user, ' подписался на ', user1)
            else:
                Contact.objects.filter(user_from=request.user,
                                       user_to=user1).delete()
            return JsonResponse({'status':'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status':'ko'})
    return JsonResponse({'status':'ko'})

# def track(request):
#     # Показать все действия по умолчанию
#     actions = Action.objects.exclude(user=request.user)
#     following_ids = request.user.following.values_list('id',
#                                                        flat=True)
#     if following_ids:
#         # Если пользователь следит за другими, извлекайте только их действия
#         actions = actions.filter(user_id__in=following_ids) \
#             .select_related('user', 'user__profile') \
#             .prefetch_related('target')
#     actions = actions[:10]
#
#     context = {'actions': actions, }
#
#     return render(request, 'accounts/user/track.html', context)


@login_required
def track(request):
    # Показать все действия по умолчанию
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list('id',
                                                       flat=True)
    if following_ids:
        # Если пользователь следит за другими, извлекайте только их действия
        actions = actions.filter(user_id__in=following_ids) \
            .select_related('user', 'user__profile') \
            .prefetch_related('target')
        paginator = Paginator(actions, 10)
        page = request.GET.get('page')
        try:
            actions = paginator.page(page)
        except PageNotAnInteger:
            # Если страница не является целым числом
            actions = paginator.page(1)
        except EmptyPage:
            if request.is_ajax():
                # Если запрос AJAX и страница вне диапазона
                # вернуть пустую страницу
                return HttpResponse('')
            # Если страница находится вне диапазона доставить последнюю страницу результатов
            actions = paginator.page(paginator.num_pages)
        if request.is_ajax():
            return render(request,
                          'accounts/user/track_ajax.html',
                          {'section': 'actions', 'actions': actions})
        return render(request,
                      'accounts/user/track.html',
                      {'section': 'actions', 'actions': actions})

accounts/templates/accounts/user/detail.html
{% extends 'python4bear/base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block title %}{{ view_user.get_full_name }}{% endblock %}

{% block sidebar %}
    <li class="breadcrumb-item"><a href="{% url "accounts:user_list" %}">People</a></li>

    {% if not view_user.get_full_name %}
        <li class="breadcrumb-item active">{{ view_user }}</li>
        {% else %}
        <li class="breadcrumb-item active">{{ view_user.get_full_name }}</li>
    {% endif %}
{% endblock sidebar%}

{% block content %}

    <div class="profile-info">

    {% if view_user.profile.photo %}
        <img class="img-circle" src="{{ view_user.profile.photo.crop.160x160 }}">
        {% else %}
         <img src="{% static 'img/avatar.svg' %}" alt="" class="w-50">
        {% endif %}

    </div>

    {% with total_followers=view_user.followers.count %}
        <span class="count">
            <span class="total">{{ total_followers }}</span>
            follower{{ total_followers|pluralize }}
        </span>



        {% if request.user.id != view_user.id %}
        <a href="#" data-id="{{ view_user.id }}" data-action="{% if request.user in view_user.followers.all %}un{% endif %}follow" class="btn btn-default follow button">
            {% if request.user not in view_user.followers.all and request.user != view_user%}
                Follow
            {% else %}
                Unfollow
            {% endif %}
        </a>
        {% endif %}

{#        <h2>{{ view_user.followers.all }}</h2>#}
        <h2>Сущего картинки:</h2>

        <div id="image-list" class="image-container">
            {% include "images/image/list_ajax.html" with images=view_user.images_created.all %}
        </div>
    {% endwith %}
{% endblock %}

{% block domready %}
    $('a.follow').click(function(e){
        e.preventDefault();
        $.post('{% url "accounts:user_follow" %}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
            function(data){
                if (data['status'] == 'ok')
                {
                    var previous_action = $('a.follow').data('action');

                    // toggle data-action
                    $('a.follow').data('action', previous_action == 'follow' ? 'unfollow' : 'follow');

                    // toggle link text
{#                    $('a.follow').text(previous_action == 'follow' ? 'Unfollow' : 'Follow');#}

                    // update total followers
                    var previous_followers = parseInt($('span.count .total').text());
                    $('span.count .total').text(previous_action == 'follow' ? previous_followers + 1 : previous_followers - 1);
                }
        });
    });
{% endblock domready %}

accounts/templates/accounts/user/list.html
{% extends 'python4bear/base.html' %}

{% block title %}People{% endblock %}

{% block sidebar %}
    <li class="breadcrumb-item active">People</li>
{% endblock sidebar%}

{% block content %}
    <div id="user-list">
        {% include "accounts/user/list_ajax.html" %}
    </div>
{% endblock %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200;
        if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
		    block_request = true;
		    page += 1;
		    $.get('?page=' + page, function(data) {
		        if(data == '')
		        {
		            empty_page = true;
		        }
		        else {
                    block_request = false;
                    $('#user-list').append(data);
    	        }
            });
    	}
    });
{% endblock %}

accounts/templates/accounts/user/list_ajax.html
{% load static %}
{% load counter %}

<div class="row">

        {% for user in users %}

            <div class="user">
                <a href="{{ user.get_absolute_url }}">
                    {% if user.profile.photo %}
        <img class="img-circle" src="{{ user.profile.photo.crop.150x150 }}">
        {% else %}
         <img src="{% static 'img/avatar.svg' %}" alt="" width="150">
        {% endif %}
                </a>

                 <span>
                    <a href="{{ user.get_absolute_url }}" class="title">{{ user.get_full_name }}
                    {% if not user.first_name %}
            {{ user }}
            {% endif %}
                    </a>

                     <span>|        {% with total_images_created=user.images_created.count %}
                         пинов  -  {{ total_images_created }}
                        {% endwith %}</span>

                     <span>|        {% with total_posts_created=user.posts.count %}
                         постов  -  {{ total_posts_created }}
                        {% endwith %}</span>

                </span>

                <hr>

</div>

        {% endfor %}

    </div>

accounts/templates/accounts/user/track.html
{% extends 'python4bear/base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block title %}Track{% endblock %}
{% block sidebar %}
    <li class="breadcrumb-item active">Track</li>
{% endblock sidebar%}


{% block content %}
    <div id="track-list">
        {% include "accounts/user/track_ajax.html" %}
    </div>
{% endblock %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200;
        if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
		    block_request = true;
		    page += 1;
		    $.get('?page=' + page, function(data) {
		        if(data == '')
		        {
		            empty_page = true;
		        }
		        else {
                    block_request = false;
                    $('#track-list').append(data);
    	        }
            });
    	}
    });
{% endblock %}

accounts/templates/accounts/user/track_ajax.html
{% load static %}
{% load counter %}

<div class="row">

{% block content %}
        <div class="container-fluid">
		<!-- Center Column -->
		<div class="col-sm-10">
			<!-- Articles -->
			<div class="row">
                <div class="panel-body">
                    <h2>What's happening - Всмысле новости:)</h2>
                    <hr>
                    <div id="action-list">
                        {% for action in actions %}
                            {% include "actions/detail.html" %}
                        {% endfor %}
                    </div>
                </div>
            </div>
		</div><!--/Center Column-->
	  <!-- Right Column -->
	  {% include 'python4bear/rait_colum.html' %}
	  </div><!--/container-fluid-->
{% endblock content%}

</div>