accounts/urls.py
from django.conf.urls import url
from . import views
from django.urls import reverse_lazy

from django.contrib.auth.views import (
    LoginView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)

urlpatterns = [
    # Страница входа.
    url(r'^login/$', LoginView.as_view
    (template_name='accounts/registration/login.html'), name='login'),
    # Страница выхода.
    url(r'^logout/$', views.logout_view, name='logout'),
    #регистрация вроде, как...
    url(r'^signup/$', views.signup, name='signup'),
    # ссылка на изменение имяни, фамилии и почты вобщем настройки аккаунта
    url(r'^accounts/profile/$', views.edit_account, name='my_account'),


    # смена пароля под своим аккаунтом
    url(r'^password-change/$', PasswordChangeView.as_view(
        template_name='accounts/registration/password_change.html',
        success_url=reverse_lazy('accounts:password_change_done')
    ),
        name='password_change'),

    url(r'^password-change-done/$', PasswordChangeDoneView.as_view(
        template_name='accounts/registration/password_change_done.html'),
        # если что лизи
        name='password_change_done'),

    # Если забыли пароль вот это всё решит ваши проблемы |
    url(r'^password-reset/$', PasswordResetView.as_view(
        template_name='accounts/registration/password_reset.html',
        email_template_name='accounts/registration/password_reset_email.html',
        success_url=reverse_lazy('accounts:password_reset_done'),
    ),
        name='password_reset'),

    url(r'^password-reset/done/$', PasswordResetDoneView.as_view(
        template_name='accounts/registration/password_reset_done.html',),
        name='password_reset_done'),

    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        PasswordResetConfirmView.as_view(
            template_name='accounts/registration/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'),

    url(r'^password-reset/complete/$',
        PasswordResetCompleteView.as_view(
            template_name='accounts/registration/password_reset_complete.html',
        ),
        name='password_reset_complete'),


    # только так сначало фолловерз, а потом все для него иначе джскрипт не сработает
    url(r'^users/followers/$', views.user_follow, name='user_follow'),

    # лист пользователей
    url(r'^users/$', views.user_list, name='user_list'),

    # конкретный юзер
    url(r'^users/(?P<username>[-\w]+)/$',
        views.user_detail, name='user_detail'),
    # новости по сути
    url(r'^track/$', views.track, name='track'),




]

images/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # создание картинки для сайта спомощю джаваскрипта
    url(r'^create/$', views.image_create, name='create'),
    # детали картинки если слунга не будет будет ошибка!!
    url(r'^detail/(?P<slug>[-\w]+)/$', views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    #url(r'^ranking/$', views.image_ranking, name='create'),
    # поидее все картинки с панигацией, но посмотрим
    url(r'^$', views.image_list, name='list'),
]

my_blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from django.contrib.sitemaps.views import sitemap
from python4bear.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'', include('python4bear.urls', namespace='python4bear')),
    url(r'', include('accounts.urls', namespace='accounts')),
    url(r'', include('search.urls', namespace='search')),
    url(r'^images/', include('images.urls', namespace='images')),
    url(r'^polls/', include('polls.urls', namespace='polls')),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    url('^', include('django.contrib.auth.urls')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/forms.py
from django import forms
from .models import Image, TwitImage
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify


class ImageCreateForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput,
        }

    def save(self, force_insert=False, force_update=False, commit=True):
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title),
                                    image_url.rsplit('.', 1)[1].lower())

        # скачать изображение с данного URL
        response = request.urlopen(image_url)
        image.image.save(image_name,
                         ContentFile(response.read()),
                         save=False)
        if commit:
            image.save()
        return image

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg', 'png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('Данный URL-адрес не соответствует допустимым расширениям изображений.')
        return url


class TwitImageForm(forms.ModelForm):
    text = forms.CharField(label='Твит',
        widget=forms.Textarea(attrs={'rows': 5,
                                     'placeholder': 'Ну давай странник, срази всех остроумием.'}),
        max_length=200,
        help_text='Максимальная длина комента 200 символов, в двух словах о изображении.',
    )
    class Meta:
        model = TwitImage
        fields = ['text']

images/templates/images/image/create.html
{% extends 'python4bear/base.html' %}
{% load bootstrap3 %}

{% block title %}Загрузка image{% endblock %}
   {% block sidebar %}
<h4>Загрузка image...</h4>
    {% endblock sidebar%}
{% block content %}
    <img src="{{ request.GET.url }}" class="image-preview">
    <form action="" method="post">
        {% bootstrap_form form %}
        {% csrf_token %}
        <button type="submit" class="btn btn-success pull-left" value="">Загрузить картинку!</button>
    </form>
{% endblock %}

images/templates/images/image/detail.html
{% extends 'python4bear/base.html' %}
{% load static %}
{% load bootstrap3 %}
{% load counter %}

{% block title %}{{ image.title }}{% endblock %}

   {% block sidebar %}
       <li class="breadcrumb-item"><a href="{% url "images:list" %}">Images</a></li>
       <li class="breadcrumb-item active">{{ image.title }}</li>
    {% endblock sidebar%}

{% block content %}

    <div class="col-md-4">

    <a href="{{ image.image.url }}">
    <img src="{{ image.image.url }}" class="image-detail">
    </a>
<span>Просмотров: {% page_views image.get_absolute_url %}</span>
{% with total_likes=image.users_like.count users_like=image.users_like.all %}

    <div class="image-info">
                <div>
                    <span class="count">
                        <span class="total">{{ total_likes }}</span>
                        like{{ total_likes|pluralize }}
                    </span>
                    <a href="#" data-id="{{ image.slug }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="btn btn-default like button">
                        {% if request.user not in users_like %}
                            Like
                        {% else %}
                            Unlike
                        {% endif %}
                    </a>
                </div>

            {{ image.description|linebreaks }}
        </div>


<div class="image-likes">
            {% for user in image.users_like.all %}

                    {% if user.profile.photo %}
                  <img class="img-circle" src="{{ MEDIA_URL }}{{ user.profile.photo.crop.50x50 }}">
                        {% if not user.first_name %}
                            <p>{{ user }}</p>
                            {% endif %}
                    <p>{{ user.first_name }}</p>
                    {% else %}
                  <img src="{% static 'img/avatar.svg' %}" alt="{{ user }}" class="w-50">
                        <p>{{ user }}</p>
                    {% endif %}

            {% empty %}
                Этот образ пока никому не нравится.
            {% endfor %}
        </div>
    {% endwith %}
</div>

    <div class="row justify-content-right">

  <div class="col-md-4 col-md-push-4">
<h3>Эмоции людей :</h3>
     <hr><div class="commentclin">
  {% for twit in twits %}
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-2">
              {% if twit.owner.profile.photo %}
                  <img class="img-circle" src="{{ MEDIA_URL }}{{ twit.owner.profile.photo.crop.50x50 }}">
              {% else %}
                  <img src="{% static 'img/avatar.svg' %}" alt="{{ twit.owner.username }}" class="w-50">
              {% endif %}
            <br>
          </div>
          <div class="col-xs-10">
            <div class="row mb-3">
              <div class="col-xs-6">
                <strong class="text-muted">{{ twit.owner.username }}</strong>
              </div>
              <div class="col-xs-6 text-right">
                <small class="text-muted">{{ twit.date_added }}</small>
              </div>
            </div>
            {{ twit.text|safe }}
          </div>
        </div>
      </div>
    </div>

    {% endfor %}


    {% if user.is_authenticated %}
            <form action="{% url 'images:detail' image.slug%}" method='post'>
            {% csrf_token %}
            {% bootstrap_form form %}
            <button name='submit' class="btn btn-primary">Твитнуть</button>
            </form>
        {% else %}
            <p>Что бы оставлять коментарии выполните - <a href="{% url 'accounts:login' %}?next={{ request.get_full_path|urlencode }}"><i>Вход</i></a></p>
            <p>Либо пройдите процедуру - <a href="{% url 'accounts:signup' %}?next={{ request.get_full_path|urlencode }}"><i>Регистрация</i></a></p>
        {% endif %}
  </div>
  </div>
    </div>



{% endblock %}

{% block domready %}
    $('a.like').click(function(e){
        e.preventDefault();
        $.post('{% url "images:like" %}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
            function(data){
                if (data['status'] == 'ok')
                {
                    var previous_action = $('a.like').data('action');

                    // toggle data-action
                    $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
                    // toggle link text
                    $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

                    // update total likes
                    var previous_likes = parseInt($('span.count .total').text());
                    $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
                }
        });
    });
{% endblock %}

images/templates/images/image/list.html
{% extends 'python4bear/base.html' %}

{% block title %}Images{% endblock %}

{% block sidebar %}
    <li class="breadcrumb-item active">Images in...</li>
    {% endblock sidebar%}

{% block content %}
    <div id="image-list">
        {% include "images/image/list_ajax.html" %}
    </div>
{% endblock %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200;
        if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
		    block_request = true;
		    page += 1;
		    $.get('?page=' + page, function(data) {
		        if(data == '')
		        {
		            empty_page = true;
		        }
		        else {
                    block_request = false;
                    $('#image-list').append(data);
    	        }
            });
    	}
    });
{% endblock %}

images/templates/images/image/list_ajax.html
{% load static %}
{% load counter %}
<link rel="stylesheet" href="{% static 'css/image_app.css' %}">

<div class="row">
    {% for image in images %}
      <div class="col-md-4 portfolio-item">
        <div class="image">
          <a href="{{ image.get_absolute_url }}" class="title">{{ image.title }}</a>
            <a href="{{ image.get_absolute_url }}">
              <img src="{{ image.image.crop.320x400 }}" class="image-detail">
            </a>
            <br>
          <span>Просмотров: {% page_views image.get_absolute_url %}</span>
        </div>
      </div>
{% endfor %}
</div>

images/templates/images/image/ranking.html
{% extends 'python4bear/base.html' %}
{% block title %}Images ranking{% endblock %}

{% block content %}
    <h1>Images ranking</h1>
    <ol>
    {% for image in most_viewed %}
        <li>
            <a href="{{ image.get_absolute_url }}">
                {{ image.title }}
            </a>
        </li>
    {% empty %}
    {% endfor %}
    </ol>
{% endblock %}