images/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # создание картинки для сайта спомощю джаваскрипта
    url(r'^create/$', views.image_create, name='create'),
    # детали картинки если слунга не будет будет ошибка!!
    url(r'^detail/(?P<slug>[-\w]+)/$', views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    #url(r'^ranking/$', views.image_ranking, name='create'),
    # поидее все картинки с панигацией, но посмотрим
    url(r'^$', views.image_list, name='list'),
]

my_blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from django.contrib.sitemaps.views import sitemap
from python4bear.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'', include('python4bear.urls', namespace='python4bear')),
    url(r'', include('accounts.urls', namespace='accounts')),
    url(r'', include('search.urls', namespace='search')),
    url(r'^images/', include('images.urls', namespace='images')),
    url(r'^polls/', include('polls.urls', namespace='polls')),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    url('^', include('django.contrib.auth.urls')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python4bear/urls.py
from django.conf.urls import url
from . import views

from .feeds import LatestPostsFeed

urlpatterns = [
    #привет страница
    url(r'^hell/$', views.hell, name='hell'),

    #основаная страница - все темы
    url(r'^$', views.home, name='home'),

    # подробно тема, и список постов
    url(r'^posts_all/(?P<pk>\d+)/$', views.posts_all, name='posts_all'),
    url(r'^tag/(?P<pk>\d+)/(?P<tag_slug>[-\w]+)/$', views.posts_all, name='post_all_by_tag'),

    # подробно пост и коменты
    url(r'^topic/(?P<pk>\d+)/view_post/'\
        r'(?P<post_name>[-\w]+)/$', views.view_post, name='view_post'),

    # добавление поста
    url(r'^post/(?P<pk>\d+)/new/$', views.new_post, name='new_post'),

    # редактирование темы хозяином темы
    url(r'^topic/(?P<pk>\d+)/edit_post/'\
        r'(?P<post_name>[-\w]+)/$', views.edit_post, name='edit_post'),

    #поделиться сообщением
    url(r'^(?P<post_name>[-\w]+)/share/$', views.post_share, name='post_share'),

    #канал RSS нафиг он только нужен не знаю
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),

]

search/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^search/$', views.index, name='index'),
]

search/templates/search/index.html
{% extends 'python4bear/base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block sidebar %}
    <h3>Поиск <b>"{{ question }}"</b></h3>
{% endblock sidebar%}

{% block content %}
        <div class="container-fluid">

		<!-- Center Column -->
		<div class="col-sm-10">
        <hr>
    {% if posts %}
        {% for post in posts %}
          {% if post.status == 'published'%}
			<!-- Articles -->
			<div class="row">

				<article class="col-xs-10">

					<h2>{{ post.title }}</h2>

                    {% if post.image %}
                    <img class="kartinka" src="{{ MEDIA_URL }}{{ post.image.url }}" alt="" title="" height="200">
                    {% endif %}
					<div class="hollitexst">{{ post.text|safe|truncatewords:30|linebreaks }}</div>
					<div class="mt-3">
                        <a href="{% url 'python4bear:view_post' post.topic.pk post.slug %}" class="btn btn-default" role="button">Ознакомиться</a>
                    </div>
					<p class="pull-right"><span class="tag tag-default">keyword:</span> <span class="tag tag-default">
                        {% for tag in post.tags.all %}
                        <a href="{% url "python4bear:post_all_by_tag" post.topic.pk tag.slug %}">
                        {{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </span></p>

					<ul class="list-inline">
						<li class="list-inline-item"><a href="#">{{ post.publish|date:'M d, Y' }}</a></li>
                        <li class="list-inline-item"><a href="#"><span class="glyphicon glyphicon-comment"></span> {{  post.comment.count }} Комменты</a></li>
						<li class="list-inline-item"><a href="#"><span class="glyphicon glyphicon-share"></span> {{ post.views }} Просмотры</a></li>
					</ul>

				</article>
			</div>
			<hr class="bl">

         {% endif %}
      {% endfor %}
    {% else %}
        <p>Не найдено публикаций по вашему запросу<br>Попробуйте повторить запрос с другой формулировкой</p>
    {% endif %}
        {% bootstrap_pagination posts url=last_question %}
		</div><!--/Center Column-->

	  <!-- Right Column -->
	  <div class="col-sm-2 hidden-xs">

			<!-- Progress Bars -->
			<div class="card">
				<div class="card-header p-b-0">
						<p class="fa fa-paperclip" aria-hidden="true">Опросы, возможно:)</p>
				</div>
                <h6>Зелёный блок</h6>
				<div class="card-block">
                     <div class="progress">
                    <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="35"
                         aria-valuemin="0" aria-valuemax="100" style="width:49%">49% Грин</div>
                    </div>
                <h6>Красный блок</h6>
                     <div class="progress">
                    <div class="progress-bar progress-bar-danger progress-bar-striped active" role="progressbar" aria-valuenow="35"
                         aria-valuemin="0" aria-valuemax="100" style="width:75%">75% Рэд </div>
                    </div>
                <h6>Оранжевы блок</h6>
                     <div class="progress">
                    <div class="progress-bar progress-bar-warning progress-bar-striped active" role="progressbar" aria-valuenow="35"
                         aria-valuemin="0" aria-valuemax="100" style="width:40%">40% Рыжий</div>
                    </div>
                <h6>Синий блок</h6>
                    <div class="progress">
                    <div class="progress-bar progress-bar-inf progress-bar-striped active" role="progressbar" aria-valuenow="35"
                         aria-valuemin="0" aria-valuemax="200" style="width:65%">65% Небесный</div>
                    </div>
				</div>
			</div>



          <!-- Carousel container -->
<h4 class="text-center slide" data-ride="carousel" style="width:180px;margin:auto;">Добрые самаритяне</h4>
<div id="my-pics" class="carousel slide" data-ride="carousel" style="width:180px;margin:auto;">

<!-- Indicators -->
<ol class="carousel-indicators">
<li data-target="#my-pics" data-slide-to="0" class="active"></li>
<li data-target="#my-pics" data-slide-to="1"></li>
<li data-target="#my-pics" data-slide-to="2"></li>
</ol>

<!-- Content -->

<div class="carousel-inner" role="listbox">

<!-- Slide 1 -->
<div class="item active">
<img src="holder.js/180x180?theme=lava" alt="Sunset over beach">
<div class="carousel-caption">
</div>
</div>

<!-- Slide 2 -->
<div class="item">
<img src="holder.js/180x180?theme=sky" alt="Rob Roy Glacier">
<div class="carousel-caption">
</div>
</div>

<!-- Slide 3 -->
<div class="item">
<img src="holder.js/180x180?theme=industrial" alt="Longtail boats at Phi Phi">
<div class="carousel-caption">
</div>
</div>

</div>

<!-- Previous/Next controls -->
<a class="left carousel-control" href="#my-pics" role="button" data-slide="prev">
<span class="icon-prev" aria-hidden="true"></span>
<span class="sr-only">Previous</span>
</a>
<a class="right carousel-control" href="#my-pics" role="button" data-slide="next">
<span class="icon-next" aria-hidden="true"></span>
<span class="sr-only">Next</span>
</a>

</div>

	  </div><!--/Right Column -->

	</div><!--/container-fluid-->

{% endblock content%}

{% block footer %}
{% endblock footer %}