accounts/urls.py
from django.conf.urls import url
from . import views
from django.urls import reverse_lazy

from django.contrib.auth.views import (
    LoginView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)

urlpatterns = [
    # Страница входа.
    url(r'^login/$', LoginView.as_view
    (template_name='accounts/registration/login.html'), name='login'),
    # Страница выхода.
    url(r'^logout/$', views.logout_view, name='logout'),
    #регистрация вроде, как...
    url(r'^signup/$', views.signup, name='signup'),
    # ссылка на изменение имяни, фамилии и почты вобщем настройки аккаунта
    url(r'^accounts/profile/$', views.edit_account, name='my_account'),


    # смена пароля под своим аккаунтом
    url(r'^password-change/$', PasswordChangeView.as_view(
        template_name='accounts/registration/password_change.html',
        success_url=reverse_lazy('accounts:password_change_done')
    ),
        name='password_change'),

    url(r'^password-change-done/$', PasswordChangeDoneView.as_view(
        template_name='accounts/registration/password_change_done.html'),
        # если что лизи
        name='password_change_done'),

    # Если забыли пароль вот это всё решит ваши проблемы |
    url(r'^password-reset/$', PasswordResetView.as_view(
        template_name='accounts/registration/password_reset.html',
        email_template_name='accounts/registration/password_reset_email.html',
        success_url=reverse_lazy('accounts:password_reset_done'),
    ),
        name='password_reset'),

    url(r'^password-reset/done/$', PasswordResetDoneView.as_view(
        template_name='accounts/registration/password_reset_done.html',),
        name='password_reset_done'),

    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        PasswordResetConfirmView.as_view(
            template_name='accounts/registration/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'),

    url(r'^password-reset/complete/$',
        PasswordResetCompleteView.as_view(
            template_name='accounts/registration/password_reset_complete.html',
        ),
        name='password_reset_complete'),


    # только так сначало фолловерз, а потом все для него иначе джскрипт не сработает
    url(r'^users/followers/$', views.user_follow, name='user_follow'),

    # лист пользователей
    url(r'^users/$', views.user_list, name='user_list'),

    # конкретный юзер
    url(r'^users/(?P<username>[-\w]+)/$',
        views.user_detail, name='user_detail'),
    # новости по сути
    url(r'^track/$', views.track, name='track'),




]

images/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # создание картинки для сайта спомощю джаваскрипта
    url(r'^create/$', views.image_create, name='create'),
    # детали картинки если слунга не будет будет ошибка!!
    url(r'^detail/(?P<slug>[-\w]+)/$', views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    #url(r'^ranking/$', views.image_ranking, name='create'),
    # поидее все картинки с панигацией, но посмотрим
    url(r'^$', views.image_list, name='list'),
]

my_blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from django.contrib.sitemaps.views import sitemap
from python4bear.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'', include('python4bear.urls', namespace='python4bear')),
    url(r'', include('accounts.urls', namespace='accounts')),
    url(r'', include('search.urls', namespace='search')),
    url(r'^images/', include('images.urls', namespace='images')),
    url(r'^polls/', include('polls.urls', namespace='polls')),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    url('^', include('django.contrib.auth.urls')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python4bear/urls.py
from django.conf.urls import url
from . import views

from .feeds import LatestPostsFeed

urlpatterns = [
    #привет страница
    url(r'^hell/$', views.hell, name='hell'),

    #основаная страница - все темы
    url(r'^$', views.home, name='home'),

    # подробно тема, и список постов
    url(r'^posts_all/(?P<pk>\d+)/$', views.posts_all, name='posts_all'),
    url(r'^tag/(?P<pk>\d+)/(?P<tag_slug>[-\w]+)/$', views.posts_all, name='post_all_by_tag'),

    # подробно пост и коменты
    url(r'^topic/(?P<pk>\d+)/view_post/'\
        r'(?P<post_name>[-\w]+)/$', views.view_post, name='view_post'),

    # добавление поста
    url(r'^post/(?P<pk>\d+)/new/$', views.new_post, name='new_post'),

    # редактирование темы хозяином темы
    url(r'^topic/(?P<pk>\d+)/edit_post/'\
        r'(?P<post_name>[-\w]+)/$', views.edit_post, name='edit_post'),

    #поделиться сообщением
    url(r'^(?P<post_name>[-\w]+)/share/$', views.post_share, name='post_share'),

    #канал RSS нафиг он только нужен не знаю
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),

]

search/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^search/$', views.index, name='index'),
]

python4bear/forms.py
from django import forms
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from ckeditor.widgets import CKEditorWidget
from .models import Post, Comment

class PostForm(forms.ModelForm):
    text = forms.CharField(label='Содержание', widget=CKEditorUploadingWidget(config_name='awesome',
                                                 attrs={ 'rows': 5, 'placeholder':
                                                   'Тут можно писать огромный пост, но подумай, оно тебе надо?'},
        )
    )
    class Meta:
        model = Post
        fields = ['title','text', ]



class CommentForm(forms.ModelForm):
    text = forms.CharField(label='Текст',
        widget=forms.Textarea(attrs={'rows': 5,
                                     'placeholder': 'Ну давай странник, срази всех остроумием.'}),
        max_length=3000,
        help_text='Максимальная длина комента 3000 символов, так что думай, прежде чем писать.',
    )
    class Meta:
        model = Comment
        fields = ['text']

class EmailPostForm(forms.Form):
    to = forms.EmailField(label='Кому отправить?',)
    comments = forms.CharField(label='Коментарий',
                               required=False,
                               widget=forms.Textarea(attrs={
                                   'placeholder': 'Что бы не забыть зачем отправил.'}))

python4bear/views.py
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render, HttpResponseRedirect
from .models import Topic, Post, Comment
from .forms import PostForm, CommentForm, EmailPostForm
from taggit.models import Tag
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse, reverse_lazy
from images.models import Image
from django.http import HttpResponse
from actions.utils import create_action


def similar():
    #
    # List of similar posts
    similar_posts = Post.published.filter()
    similar_posts = similar_posts.order_by('views')[:3]
    return similar_posts

def image_foor(request):
    image_js = Image.objects.all().order_by('-created')
    paginator = Paginator(image_js, 4)
    page = request.GET.get('page')
    try:
        image_js = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом
        image_js = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # Если запрос AJAX и страница вне диапазона
            # вернуть пустую страницу
            return HttpResponse('')
    return image_js

def hell(request):
    #Возврат html докуменда домашний страницы всех Тем.
    queryset_post = Post.objects.filter(status='published').order_by('-publish')
    page = request.GET.get('page', 1)
    paginator = Paginator(queryset_post, 3)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, поставьте первую страницу
        posts = paginator.page(1)
    except EmptyPage:
        # вероятно, пользователь попытался добавить номер страницы
        # в url, поэтому мы переходим к последней странице
        posts = paginator.page(paginator.num_pages)


    similar_posts = similar()
    image_js=image_foor(request)

    context = {'posts': posts, 'queryset_post':queryset_post, 'similar_posts': similar_posts, 'image_js':image_js}
    return render(request, 'python4bear/hell.html', context)


def home(request):
    #Возврат html докуменда домашний страницы всех Тем.
    queryset = Topic.objects.order_by('date_added')
    page = request.GET.get('page', 1)
    paginator = Paginator(queryset, 5)

    try:
        topics = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, поставьте первую страницу
        topics = paginator.page(1)
    except EmptyPage:
        # вероятно, пользователь попытался добавить номер страницы
        # в url, поэтому мы переходим к последней странице
        topics = paginator.page(paginator.num_pages)

    similar_posts = similar()
    image_js = image_foor(request)

    context = {'topics': topics, 'similar_posts': similar_posts, 'image_js':image_js,}
    return render(request, 'python4bear/home.html', context)


def posts_all(request, pk, tag_slug=None):
    """Возврат html докуменда одной Темы и всё её Посты."""
    # можно и так если без того класса Post.objects.filter(status='published')
    topic = get_object_or_404(Topic, pk=pk)
    queryset = topic.posts.order_by('-views').annotate(replies=Count('comment'))

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        queryset = queryset.filter(tags__in=[tag])

    page = request.GET.get('page', 1)
    paginator = Paginator(queryset, 10)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # fallback to the first page
        posts = paginator.page(1)
    except EmptyPage:
        # probably the user tried to add a page number
        # in the url, so we fallback to the last page
        posts = paginator.page(paginator.num_pages)

        # List of similar posts
    similar_posts = Post.published.filter(topic__pk=pk)
    similar_posts = similar_posts[:3]
    image_js = image_foor(request)

    context = {'topic':topic, 'posts':posts,
               'page': page, 'tag': tag,
               'similar_posts': similar_posts,
               'image_js': image_js,
               'sent': request.GET.get('sent', False)}

    return render(request, 'python4bear/posts_all.html', context)


def view_post(request, pk, post_name):
    """Просматриваем конкретный Пост"""
    post = get_object_or_404(Post, topic__pk=pk,
                             slug=post_name,)
    comments = post.comment.filter(active=True)

    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = CommentForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = CommentForm(request.POST, )
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.owner = request.user
            new_comment.save()

            # думал так можно заставить не считать обрати внимание как ретурн делается
            """  переносим код в модели!!!  return HttpResponseRedirect(
                '{}?sent=True'.format(reverse('python4bear:view_post',
                                              kwargs={'pk':post.topic.pk, 'post_name':post.slug})))"""
            return HttpResponseRedirect(
                '{}?sent=True'.format(post.get_absolute_url()))

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:3]
    image_js = image_foor(request)

    context = {'post':post, 'form': form,
               'comments':comments, 'similar_posts': similar_posts,
               'image_js': image_js,
               'sent': request.GET.get('sent', False)}

    return render(request, 'python4bear/view_post.html', context)


@login_required
def new_post(request, pk):
    """Добавляет новый Пост к конкретной Теме."""
    topic = get_object_or_404(Topic, pk=pk)
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = PostForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.topic = topic
            new_post.owner = request.user
            new_post.save()
            create_action(request.user, 'создал пост', new_post)
            return HttpResponseRedirect(
                '{}?sent=True'.format(reverse('python4bear:posts_all',
                                          kwargs={'pk': topic.pk})))

    context = {'topic': topic, 'form': form}
    return render(request, 'python4bear/new_post.html', context)


@login_required
def edit_post(request, pk, post_name):
    post = get_object_or_404(Post, slug=post_name,)
    topic = post.topic
    if request.method != 'POST':
        form = PostForm(instance=post)
    else:
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('python4bear:view_post', pk=pk, post_name=post.slug,)

    context = { 'topic': topic, 'post': post, 'form': form}
    return render(request, 'python4bear/edit_post.html', context)


@login_required
def post_share(request, post_name):
    # Retrieve post by id
    post = get_object_or_404(Post, slug=post_name, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = 'Почитай отца и мать и возможно пост про {}'.format(post.title)
            message = 'Тема "{}" адрес {}\n\'коментарий: {}'.format(post.title, post_url, cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request, 'python4bear/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

python4bear/templates/python4bear/base.html
{% load static %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

{#    <link type="image/x-icon" rel="shortcut icon" href="favicon.ico">#}

    <title>{% block title %}Python4Bear{% endblock title%}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">

    {% block stylesheet %}
    {#  создаем блок для того чтобы цсс поменять в акаунте  #}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% endblock stylesheet%}
    {% bootstrap_css %}

{% block JS %}
   <!-- jQuery -->
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- IE10 viewport bug workaround -->
	<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
	<!-- Placeholder Images -->
	<script src="{% static 'js/holder.min.js' %}"></script>
{% endblock JS %}


</head>

<body>
{% block body %}  <!-- HERE -->


    <!-- Hавигационный бар... -->
<nav class="navbar navbar-inverse">
<div class="container">
<div class="container-fluid">

<!-- BRAND -->
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#alignment-example" aria-expanded="false">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="{% url 'python4bear:hell' %}">Python4Bear</a>
</div>

<!-- COLLAPSIBLE NAVBAR -->
<div class="collapse navbar-collapse" id="alignment-example">

<!-- Links -->
<ul class="nav navbar-nav">

<li class="active"><div class="btn-group">
	 <a class="navbar-brand " href="{% url 'python4bear:home' %}">Shards</a>
  </div></li>
<li class="active"><div class="btn-group">
	 <a class="navbar-brand " href="{% url "images:list" %}">Images</a>
  </div></li>
<li class="active"><div class="btn-group">
	 <a class="navbar-brand " href="{% url "accounts:user_list" %}">People</a>
  </div></li>
<li class="active"><div class="btn-group">
	 <a class="navbar-brand " href="{% url 'accounts:track' %}">Track</a>
  </div></li>

{% if user.is_authenticated %}
  <li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Привет, {{ user.username }}!<span class="caret"></span></a>
<ul class="dropdown-menu" aria-labelledby="about-us">
<li><a class="dropdown-item" href="{% url 'accounts:my_account' %}">ред. аккаунд</a></li>
<li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Выход</a></li>
</ul>
</li>
   {% else %}
   <li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Привет, чужой!<span class="caret"></span></a>
<ul class="dropdown-menu" aria-labelledby="about-us">
    {#  для того что бы был адекватный переход и не вызывались ошибки, маст хев или нет не знаю, но работает.#}
<li><a class="dropdown-item" href="{% url 'accounts:login' %}?next={{ request.get_full_path|urlencode }}">Вход</a></li>
<li><a class="dropdown-item" href="{% url 'accounts:signup' %}?next={{ request.get_full_path|urlencode }}">Регистрация</a></li>
</ul>
</li>
{% endif %}

</ul>

<!-- Search -->

<form action="{% url 'search:index' %}" class="navbar-form navbar-right" method="get">
    <div class="input-group">
        <input id="search" name="q" type="text" class="form-control  input-sm" placeholder="Поиск">
        <span class="input-group-btn">
            <button type="submit" class="btn btn-default  input-sm">{% bootstrap_icon 'search' %}</button>
        </span>
    </div>
</form>



</div>
</div>
</div>
</nav>

  <!-- /Hавигационный бар!! -->

<div class="container">
  <ol class="breadcrumb my-4">
    {% block sidebar %}
    {% endblock sidebar%}
  </ol>
    {% block content %}
    {% endblock content%}
</div>

{% block footer %}


{% endblock footer %}
    <footer class="commentclin">
        <div class="small-footer">
        	<div class="container">
                <hr>
        		<p>

                    <a href="https://www.python.org" target="_blank">Python 3.6</a> |
                    <a href="https://www.djangoproject.com" target="_blank">Django 1.11</a> |
                    <a href="https://vk.com/id18127193" target="_blank">Contact My</a>
                     </p>


        		<p><small class="text-muted d-block">
                    <a class="btn btn-default btn-xs" href="{% url "python4bear:post_feed" %}" title="RSS">RSS</a>

                    <a href="https://github.com/dimon1986" target="_blank"
           class="btn btn-default btn-xs" role="button" title="ImGit">ImGit</a>

                    Copyright &copy; Dimon & Sony 2018
                </small></p>


        	</div>
        </div>
	</footer>

{% endblock body %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src=" http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>
    <script>
        var csrftoken = $.cookie('csrftoken');
        function csrfSafeMethod(method) {
            // эти методы HTTP не требуют защиты CSRF
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        $(document).ready(function(){
            {% block domready %}
            {% endblock %}
		});
    </script>
</body>
</html>

python4bear/templates/python4bear/edit_post.html
{% extends 'python4bear/base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block title %}Редактируем...{% endblock %}


{% block sidebar %}
  <li class="breadcrumb-item"><a href="{% url 'python4bear:home' %}">Topics</a></li>
  <li class="breadcrumb-item"><a href="{% url 'python4bear:posts_all' topic.pk %}">{{ post.topic.text }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'python4bear:view_post' topic.pk post.slug%}">{{ post.title }}</a></li>
  <li class="breadcrumb-item active">Редактируем этот Post</li>
{% endblock sidebar %}

{% block content %}

  <form action="{% url 'python4bear:edit_post' topic.pk post.slug%}" method='post'>
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button name="submit" class="btn btn-primary">Сохранить</button>
  </form>

{% endblock %}

python4bear/templates/python4bear/new_post.html
{% extends 'python4bear/base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block title %}Start a New Post{% endblock %}


{% block sidebar %}
  <li class="breadcrumb-item"><a href="{% url 'python4bear:home' %}">Topics</a></li>
  <li class="breadcrumb-item"><a href="{% url 'python4bear:posts_all' topic.pk %}">{{ topic }}</a></li>
  <li class="breadcrumb-item active">New Post</li>
{% endblock sidebar%}

{% block content %}

  <p>Новый пост:</p>

  <form action="{% url 'python4bear:new_post' topic.pk %}" method='post'>
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button name='submit' class="btn btn-primary">Добавить</button>
  </form>

{% endblock content%}

python4bear/templates/python4bear/posts_all.html
{% extends 'python4bear/base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block title %}{{ topic }}  - {{ block.super }}
{% endblock title%}

  {% block sidebar %}

        <li class="breadcrumb-item"><a href="{% url 'python4bear:home' %}">Topics</a></li>
        <li class="breadcrumb-item active">{{ topic }}</li>

  {% endblock sidebar%}

   {% block content %}
      <div class="mb-4">
        <a href="{% url 'python4bear:new_post' topic.pk %}"><button name='submit' class="btn btn-primary">New post</button></a>
      </div>


    {% if sent %}
        <h3>Ваш пост добавлен, будет проверен и если всё хорошо опубликован.</h3>
    {% endif %}

  <table class="table">
    <thead class="table-fon">
      <tr>
        <th>Пост</th>
        <th>Тварец</th>
        <th>Коментарии</th>
        <th>Просмотры</th>
        <th>Создание</th>
      </tr>
    </thead>
    <tbody>

      {% for post in posts %}
          {% if post.status == 'published'%}
              <tr>
          <td>
              <p class="mb-0">
                  <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
{#              <a href="{% url 'python4bear:view_post' topic.pk post.slug%}">{{ post.title }}</a>#}
              </p>
          </td>
          <td><small class="text-muted d-block">{{ post.owner.username }}</small></td>
                  <td class="align-middle"><span class="badge">{{ post.replies }}</span></td>
          <td>{{ post.views }}</td>

          <td><small class="text-muted d-block">{{ post.publish|date:'M d, Y H:i' }}</small></td>

        </tr>
          {% endif %}
      {% endfor %}

    </tbody>
  </table>

    {% include 'python4bear/pagination_def.html'  with page=posts %}

   {% endblock content%}

    {% block footer %}
        {% include 'python4bear/footer_box.html' %}
    {% endblock footer %}

python4bear/templates/python4bear/view_post.html
{% extends 'python4bear/base.html' %}


{% load static %}
{% load bootstrap3 %}

{% block title %}{{ post.title }}{% endblock %}



{% block sidebar %}
  <li class="breadcrumb-item"><a href="{% url 'python4bear:home' %}">Topics</a></li>
  <li class="breadcrumb-item"><a href="{% url 'python4bear:posts_all' post.topic.pk %}">{{ post.topic.text}}</a></li>
  <li class="breadcrumb-item active">{{ post.title }}</li>
{% endblock sidebar%}


{% block content %}

     <div class="mb-4">
     {% if post.owner == user %}
         <div class="mt-3">
             <a href="{% url 'python4bear:edit_post' post.topic.pk post.slug%}" class="btn btn-primary" role="button">Редактировать Пост</a>
         </div>
     {% endif %}
     </div>

    <div class="row">

				<article class="col-xs-10">
    <br>
                <div class="panel panel-default ">
                <div class="panel-heading">
                    <h2 >{{ post.title }}</h2>
                </div>

    <div class="panel-body">

    <div class="hollitexst">
    {% if post.image %}
        <img class="kartinka" src="{{ MEDIA_URL }}{{ post.image.url }}" alt="" title="" height="300">
    {% endif %}

       {{ post.text|safe }}
    </div>



    <p>
    <a href="{% url "python4bear:post_share" post.slug %}">Отправить на почту</a>
    </p>
    </div>
                </div>

    <hr><div class="commentclin">

  {% for comment in comments %}
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-2">
              {% if comment.owner.profile.photo %}
                  <img class="img-circle" src="{{ comment.owner.profile.photo.crop.60x60 }}">
              {% else %}
                  <img src="{% static 'img/avatar.svg' %}" alt="{{ comment.owner.username }}" class="w-50">
              {% endif %}
            <br>
              <small>Posts: {{ comment.owner.comment.count }}</small>
          </div>
          <div class="col-xs-10">
            <div class="row mb-3">
              <div class="col-xs-6">
                <strong class="text-muted">{{ comment.owner.username }}</strong>
              </div>
              <div class="col-xs-6 text-right">
                <small class="text-muted">{{ comment.date_added }}</small>
              </div>
            </div>

            {{ comment.text|safe }}
          </div>
        </div>
      </div>
    </div>


    {% endfor %}

    </div><hr>

    {% if not sent %}
{#        делаю через стаил так как возвращается нон и отображаетс#}
        <div style="display: none" >
        {{ post.get_views_plus }}
        </div>
        {% if user.is_authenticated %}
            <form action="{% url 'python4bear:view_post' post.topic.pk post.slug%}" method='post'>
            {% csrf_token %}
            {% bootstrap_form form %}
            <button name='submit' class="btn btn-primary">Сумничить</button>
            </form>
        {% else %}
            <p>Что бы оставлять коментарии выполните - <a href="{% url 'accounts:login' %}?next={{ request.get_full_path|urlencode }}"><i>Вход</i></a></p>
            <p>Либо пройдите процедуру - <a href="{% url 'accounts:signup' %}?next={{ request.get_full_path|urlencode }}"><i>Регистрация</i></a></p>
        {% endif %}

    {% else %}
        <h3>Ваш коментарий добавлен, будет проверен и если всё хорошо опубликован.</h3>
    {% endif %}

    </article>
    {% include 'python4bear/rait_colum.html' %}
			</div>



{% endblock content%}

{% block footer %}
    		{% include 'python4bear/footer_box.html' %}
{% endblock footer %}